---
#
# Playbook to install the ELK stack + Beats
#
- hosts: elkservers
  remote_user: vagrant
  become: yes
  become_user: root
  roles:
  - { role: java }
  - { role: elasticsearch }
  - { role: kibana }
  - { role: logstash }
  - { role: filebeat }
  - { role: filebeat-logzio }
  - { role: metricbeat }
